title: 123hp.com/setup | Install Wireless HP Printer | HP Printer Drivers
description: To setup HP Printer on any device you need to download it  and visit: www.123.hp.com/setup to get started with it.
